// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// gltfa_cpp
Rcpp::List gltfa_cpp(const arma::mat& y, const Rcpp::List& mcmc, const Rcpp::List& model, const Rcpp::List& prior, const Rcpp::List& init, const Rcpp::List& control);
RcppExport SEXP _gltfactor_gltfa_cpp(SEXP ySEXP, SEXP mcmcSEXP, SEXP modelSEXP, SEXP priorSEXP, SEXP initSEXP, SEXP controlSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type mcmc(mcmcSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type model(modelSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type prior(priorSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type init(initSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type control(controlSEXP);
    rcpp_result_gen = Rcpp::wrap(gltfa_cpp(y, mcmc, model, prior, init, control));
    return rcpp_result_gen;
END_RCPP
}
// update_H_cpp
Rcpp::List update_H_cpp(const arma::mat& y, const arma::imat& Delta_in, const arma::mat& Eta_in, const Rcpp::List& hyperpar, double nu, double q);
RcppExport SEXP _gltfactor_update_H_cpp(SEXP ySEXP, SEXP Delta_inSEXP, SEXP Eta_inSEXP, SEXP hyperparSEXP, SEXP nuSEXP, SEXP qSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const arma::imat& >::type Delta_in(Delta_inSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Eta_in(Eta_inSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type hyperpar(hyperparSEXP);
    Rcpp::traits::input_parameter< double >::type nu(nuSEXP);
    Rcpp::traits::input_parameter< double >::type q(qSEXP);
    rcpp_result_gen = Rcpp::wrap(update_H_cpp(y, Delta_in, Eta_in, hyperpar, nu, q));
    return rcpp_result_gen;
END_RCPP
}
// marg_lik
Rcpp::NumericVector marg_lik(const Rcpp::IntegerVector& index, const arma::mat& y, const arma::imat& Delta, const arma::mat& Eta, const Rcpp::List& hyperpar, bool logarithm);
RcppExport SEXP _gltfactor_marg_lik(SEXP indexSEXP, SEXP ySEXP, SEXP DeltaSEXP, SEXP EtaSEXP, SEXP hyperparSEXP, SEXP logarithmSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type index(indexSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const arma::imat& >::type Delta(DeltaSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Eta(EtaSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type hyperpar(hyperparSEXP);
    Rcpp::traits::input_parameter< bool >::type logarithm(logarithmSEXP);
    rcpp_result_gen = Rcpp::wrap(marg_lik(index, y, Delta, Eta, hyperpar, logarithm));
    return rcpp_result_gen;
END_RCPP
}
// rbetabinom_cpp
int rbetabinom_cpp(double a, double b, int size);
RcppExport SEXP _gltfactor_rbetabinom_cpp(SEXP aSEXP, SEXP bSEXP, SEXP sizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type a(aSEXP);
    Rcpp::traits::input_parameter< double >::type b(bSEXP);
    Rcpp::traits::input_parameter< int >::type size(sizeSEXP);
    rcpp_result_gen = Rcpp::wrap(rbetabinom_cpp(a, b, size));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_gltfactor_gltfa_cpp", (DL_FUNC) &_gltfactor_gltfa_cpp, 6},
    {"_gltfactor_update_H_cpp", (DL_FUNC) &_gltfactor_update_H_cpp, 6},
    {"_gltfactor_marg_lik", (DL_FUNC) &_gltfactor_marg_lik, 6},
    {"_gltfactor_rbetabinom_cpp", (DL_FUNC) &_gltfactor_rbetabinom_cpp, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_gltfactor(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
