// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// gltfa_cpp
Rcpp::List gltfa_cpp(const arma::mat& y, const Rcpp::List& mcmc, const Rcpp::List& model, const Rcpp::List& prior, const Rcpp::List& init, const Rcpp::List& control, const Rcpp::List& fixed);
RcppExport SEXP _gltfactor_gltfa_cpp(SEXP ySEXP, SEXP mcmcSEXP, SEXP modelSEXP, SEXP priorSEXP, SEXP initSEXP, SEXP controlSEXP, SEXP fixedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type mcmc(mcmcSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type model(modelSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type prior(priorSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type init(initSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type control(controlSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type fixed(fixedSEXP);
    rcpp_result_gen = Rcpp::wrap(gltfa_cpp(y, mcmc, model, prior, init, control, fixed));
    return rcpp_result_gen;
END_RCPP
}
// update_H_cpp
Rcpp::List update_H_cpp(const arma::mat& y, const arma::imat& Delta_in, const arma::mat& Eta_in, const Rcpp::List& hyperpar, double nu, double q);
RcppExport SEXP _gltfactor_update_H_cpp(SEXP ySEXP, SEXP Delta_inSEXP, SEXP Eta_inSEXP, SEXP hyperparSEXP, SEXP nuSEXP, SEXP qSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const arma::imat& >::type Delta_in(Delta_inSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Eta_in(Eta_inSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type hyperpar(hyperparSEXP);
    Rcpp::traits::input_parameter< double >::type nu(nuSEXP);
    Rcpp::traits::input_parameter< double >::type q(qSEXP);
    rcpp_result_gen = Rcpp::wrap(update_H_cpp(y, Delta_in, Eta_in, hyperpar, nu, q));
    return rcpp_result_gen;
END_RCPP
}
// update_delta_cpp
arma::imat update_delta_cpp(const arma::mat& y, const arma::imat& Delta_in, const arma::mat& Eta, const arma::vec& tau, const Rcpp::List& hyperpar);
RcppExport SEXP _gltfactor_update_delta_cpp(SEXP ySEXP, SEXP Delta_inSEXP, SEXP EtaSEXP, SEXP tauSEXP, SEXP hyperparSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const arma::imat& >::type Delta_in(Delta_inSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Eta(EtaSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type tau(tauSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type hyperpar(hyperparSEXP);
    rcpp_result_gen = Rcpp::wrap(update_delta_cpp(y, Delta_in, Eta, tau, hyperpar));
    return rcpp_result_gen;
END_RCPP
}
// update_pivots_cpp
Rcpp::List update_pivots_cpp(const arma::mat& y, const arma::imat& Delta_in, const arma::mat& Eta, const Rcpp::List& hyperpar);
RcppExport SEXP _gltfactor_update_pivots_cpp(SEXP ySEXP, SEXP Delta_inSEXP, SEXP EtaSEXP, SEXP hyperparSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const arma::imat& >::type Delta_in(Delta_inSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Eta(EtaSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type hyperpar(hyperparSEXP);
    rcpp_result_gen = Rcpp::wrap(update_pivots_cpp(y, Delta_in, Eta, hyperpar));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_gltfactor_gltfa_cpp", (DL_FUNC) &_gltfactor_gltfa_cpp, 7},
    {"_gltfactor_update_H_cpp", (DL_FUNC) &_gltfactor_update_H_cpp, 6},
    {"_gltfactor_update_delta_cpp", (DL_FUNC) &_gltfactor_update_delta_cpp, 5},
    {"_gltfactor_update_pivots_cpp", (DL_FUNC) &_gltfactor_update_pivots_cpp, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_gltfactor(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
