// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// gltfa_cpp
Rcpp::List gltfa_cpp(const arma::mat& y, const Rcpp::List& mcmc, const Rcpp::List& model, const Rcpp::List& prior, const Rcpp::List& init, const Rcpp::List& control, const Rcpp::List& fixed);
RcppExport SEXP _glt_gltfa_cpp(SEXP ySEXP, SEXP mcmcSEXP, SEXP modelSEXP, SEXP priorSEXP, SEXP initSEXP, SEXP controlSEXP, SEXP fixedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type mcmc(mcmcSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type model(modelSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type prior(priorSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type init(initSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type control(controlSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type fixed(fixedSEXP);
    rcpp_result_gen = Rcpp::wrap(gltfa_cpp(y, mcmc, model, prior, init, control, fixed));
    return rcpp_result_gen;
END_RCPP
}
// gltfa_star_cpp
Rcpp::List gltfa_star_cpp(const arma::imat& y_obs, const arma::mat& X, const Rcpp::List& thresholds, const Rcpp::IntegerVector& g_type, const Rcpp::List& mcmc, const Rcpp::List& model, const Rcpp::List& prior, const Rcpp::List& init, const Rcpp::List& control, const Rcpp::List& fixed);
RcppExport SEXP _glt_gltfa_star_cpp(SEXP y_obsSEXP, SEXP XSEXP, SEXP thresholdsSEXP, SEXP g_typeSEXP, SEXP mcmcSEXP, SEXP modelSEXP, SEXP priorSEXP, SEXP initSEXP, SEXP controlSEXP, SEXP fixedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::imat& >::type y_obs(y_obsSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type thresholds(thresholdsSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type g_type(g_typeSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type mcmc(mcmcSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type model(modelSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type prior(priorSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type init(initSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type control(controlSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type fixed(fixedSEXP);
    rcpp_result_gen = Rcpp::wrap(gltfa_star_cpp(y_obs, X, thresholds, g_type, mcmc, model, prior, init, control, fixed));
    return rcpp_result_gen;
END_RCPP
}
// compute_spurious_cpp
IntegerVector compute_spurious_cpp(List Delta_draws);
RcppExport SEXP _glt_compute_spurious_cpp(SEXP Delta_drawsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type Delta_draws(Delta_drawsSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_spurious_cpp(Delta_draws));
    return rcpp_result_gen;
END_RCPP
}
// compute_metrics_inner_cpp
List compute_metrics_inner_cpp(List Lambda_draws, List Delta_draws, NumericMatrix sigma2_draws, IntegerVector H_draws, IntegerMatrix Delta_true, NumericVector Sigma_true, NumericMatrix Omega0_r);
RcppExport SEXP _glt_compute_metrics_inner_cpp(SEXP Lambda_drawsSEXP, SEXP Delta_drawsSEXP, SEXP sigma2_drawsSEXP, SEXP H_drawsSEXP, SEXP Delta_trueSEXP, SEXP Sigma_trueSEXP, SEXP Omega0_rSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type Lambda_draws(Lambda_drawsSEXP);
    Rcpp::traits::input_parameter< List >::type Delta_draws(Delta_drawsSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type sigma2_draws(sigma2_drawsSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type H_draws(H_drawsSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type Delta_true(Delta_trueSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Sigma_true(Sigma_trueSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Omega0_r(Omega0_rSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_metrics_inner_cpp(Lambda_draws, Delta_draws, sigma2_draws, H_draws, Delta_true, Sigma_true, Omega0_r));
    return rcpp_result_gen;
END_RCPP
}
// truncnorm_lg
arma::mat truncnorm_lg(const arma::mat& y_lower, const arma::mat& y_upper, const arma::mat& mu, const arma::vec& sigma, const arma::mat& u_rand);
RcppExport SEXP _glt_truncnorm_lg(SEXP y_lowerSEXP, SEXP y_upperSEXP, SEXP muSEXP, SEXP sigmaSEXP, SEXP u_randSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type y_lower(y_lowerSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type y_upper(y_upperSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type mu(muSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type u_rand(u_randSEXP);
    rcpp_result_gen = Rcpp::wrap(truncnorm_lg(y_lower, y_upper, mu, sigma, u_rand));
    return rcpp_result_gen;
END_RCPP
}
// update_H_cpp
Rcpp::List update_H_cpp(const arma::mat& y, const arma::imat& Delta_in, const arma::mat& Eta_in, const Rcpp::List& hyperpar, double nu, int Hmax, double q);
RcppExport SEXP _glt_update_H_cpp(SEXP ySEXP, SEXP Delta_inSEXP, SEXP Eta_inSEXP, SEXP hyperparSEXP, SEXP nuSEXP, SEXP HmaxSEXP, SEXP qSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const arma::imat& >::type Delta_in(Delta_inSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Eta_in(Eta_inSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type hyperpar(hyperparSEXP);
    Rcpp::traits::input_parameter< double >::type nu(nuSEXP);
    Rcpp::traits::input_parameter< int >::type Hmax(HmaxSEXP);
    Rcpp::traits::input_parameter< double >::type q(qSEXP);
    rcpp_result_gen = Rcpp::wrap(update_H_cpp(y, Delta_in, Eta_in, hyperpar, nu, Hmax, q));
    return rcpp_result_gen;
END_RCPP
}
// update_delta_cpp
arma::imat update_delta_cpp(const arma::mat& y, const arma::imat& Delta_in, const arma::mat& Eta, const arma::vec& tau, const Rcpp::List& hyperpar, const bool random_scan);
RcppExport SEXP _glt_update_delta_cpp(SEXP ySEXP, SEXP Delta_inSEXP, SEXP EtaSEXP, SEXP tauSEXP, SEXP hyperparSEXP, SEXP random_scanSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const arma::imat& >::type Delta_in(Delta_inSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Eta(EtaSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type tau(tauSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type hyperpar(hyperparSEXP);
    Rcpp::traits::input_parameter< const bool >::type random_scan(random_scanSEXP);
    rcpp_result_gen = Rcpp::wrap(update_delta_cpp(y, Delta_in, Eta, tau, hyperpar, random_scan));
    return rcpp_result_gen;
END_RCPP
}
// update_pivots_cpp
Rcpp::List update_pivots_cpp(const arma::mat& y, const arma::imat& Delta_in, const arma::mat& Eta, const Rcpp::List& hyperpar);
RcppExport SEXP _glt_update_pivots_cpp(SEXP ySEXP, SEXP Delta_inSEXP, SEXP EtaSEXP, SEXP hyperparSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const arma::imat& >::type Delta_in(Delta_inSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Eta(EtaSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type hyperpar(hyperparSEXP);
    rcpp_result_gen = Rcpp::wrap(update_pivots_cpp(y, Delta_in, Eta, hyperpar));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_glt_gltfa_cpp", (DL_FUNC) &_glt_gltfa_cpp, 7},
    {"_glt_gltfa_star_cpp", (DL_FUNC) &_glt_gltfa_star_cpp, 10},
    {"_glt_compute_spurious_cpp", (DL_FUNC) &_glt_compute_spurious_cpp, 1},
    {"_glt_compute_metrics_inner_cpp", (DL_FUNC) &_glt_compute_metrics_inner_cpp, 7},
    {"_glt_truncnorm_lg", (DL_FUNC) &_glt_truncnorm_lg, 5},
    {"_glt_update_H_cpp", (DL_FUNC) &_glt_update_H_cpp, 7},
    {"_glt_update_delta_cpp", (DL_FUNC) &_glt_update_delta_cpp, 6},
    {"_glt_update_pivots_cpp", (DL_FUNC) &_glt_update_pivots_cpp, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_glt(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
