# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Internal Rcpp sampler stub for gltfa
#'
#' This is a placeholder implementation used to validate the R-to-C++
#' interface and package compilation. The full sampler will iterate the
#' Section 3 updates in the paper.
#'
#' @noRd
gltfa_cpp <- function(y, mcmc, model, prior, init, control) {
    .Call('_gltfactor_gltfa_cpp', PACKAGE = 'gltfactor', y, mcmc, model, prior, init, control)
}

