# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

gltfa_cpp <- function(y, mcmc, model, prior, init, control) {
    .Call('_gltfactor_gltfa_cpp', PACKAGE = 'gltfactor', y, mcmc, model, prior, init, control)
}

#' @keywords internal
#' @noRd
update_H_cpp <- function(y, Delta_in, Eta_in, hyperpar, nu, q = 0.5) {
    .Call('_gltfactor_update_H_cpp', PACKAGE = 'gltfactor', y, Delta_in, Eta_in, hyperpar, nu, q)
}

#' Compute marginal likelihood for a single row i of Delta
#' 
#' Matches OLDSTUFF/aux.R::marg.lik.i
#' 
#' @keywords internal
NULL

#' Marginal likelihood for multiple rows
#' 
#' Compute marginal likelihood for specified rows of Delta.
#' Matches OLDSTUFF/aux.R::marg.lik
#' 
#' @param index 1-based indices of rows to compute marginal likelihood for
#' @param y Response matrix (T x m)
#' @param Delta Binary indicator matrix (m x H)
#' @param Eta Factor matrix (H x T)
#' @param hyperpar List with elements: kappa, a_s, b_s
#' @param logarithm If TRUE, return log marginal likelihood; else exponentiate
#' 
#' @return Numeric vector of marginal likelihoods
#' 
#' @keywords internal
#' @noRd
marg_lik <- function(index, y, Delta, Eta, hyperpar, logarithm = TRUE) {
    .Call('_gltfactor_marg_lik', PACKAGE = 'gltfactor', index, y, Delta, Eta, hyperpar, logarithm)
}

#' Sample from beta-binomial distribution
#' 
#' Matches OLDSTUFF/aux.R::rbetabinom
#' 
#' @param a Shape parameter 1
#' @param b Shape parameter 2
#' @param size Number of trials
#' 
#' @return Integer sample from beta-binomial(size, a, b)
#' 
#' @keywords internal
#' @noRd
rbetabinom_cpp <- function(a, b, size) {
    .Call('_gltfactor_rbetabinom_cpp', PACKAGE = 'gltfactor', a, b, size)
}

